### ISSUE TITLE
Tweak output regex

### ISSUE THREAD

**Issue by jonsterling** [freebroccolo/vscode-redprl#1]
With a few tweaks to the regex, it looks like we should be able to all the same reporting stuff that we have in the emacs/flycheck setup.

- [x] In RedPRL, we have a Print command that prints information about a user-defined operator or theorem. I believe this dumps an `Info` message
- [x] Currently, parse errors are not reported

(At least, these were the case when I used this last night.)

**Comment by freebroccolo** [comment]
I just fixed the second one. Syntax errors should now be reported properly.

**Comment by freebroccolo** [comment]
The `Print` command now shows the expected output I think. I also implemented a symbol provider feature which you can pull up with ⇧⌘O.

![info](https://cloud.githubusercontent.com/assets/151197/19869524/52c5f764-9f72-11e6-9bbc-b3214070ed35.png)

**Comment by freebroccolo** [comment]
@jonsterling by the way, regarding parse errors, it would nice if the `redprl` binary would just report the error but try to continue parsing the rest of the file. That would give a better experience with the way diagnostics work here.

So if an error is encountered during parsing, record the error but don't halt. Instead, begin scanning forward in the token stream until the starting token for a new top-level item is found (or EOF). This should be pretty straightforward especially since there is no nesting of items that would potentially make things more complicated.

**Comment by jonsterling** [comment]
@freebroccolo This looks sweet!!

Re: parsing, that sounds very interesting... I'm not sure I understand exactly how to do that in the current setup (which is a straightforward mlyacc parser + grammar combo), but I'd definitely be interested in that.

**Comment by wilcoxjay** [comment]
<barging into this conversation uninvited> 

I don't think there's any direct way of assking mlyacc to this. One idea would be to "chop off" the topmost layer of the grammar (the nonterminal `sign`). Then, instead of parsing a whole RedPRL signature in one go, you have a loop parse one command at a time. If a command fails to parse, manually scan ahead in the token stream until you see a start-of-declaration token, and go around the loop again.

**Comment by jonsterling** [comment]
@wilcoxjay @freebroccolo Makes me wish I could use Menhir for this 😄 It seems like this might be possible there...

**Comment by wilcoxjay** [comment]
port to OCaml, obviously!!1!

**Comment by freebroccolo** [comment]
I think what @wilcoxjay describes might be doable actually. It would probably be a bit more bookkeeping work, but if you switch to parsing at the command/item level and construct the signature from the results manually, it should work I think. So you could have the item level parser return something like `(result option, int)`, where the `int` is how much of the stream is consumed and will be used as the offset to calculate where you will restart the parser.

**Comment by jonsterling** [comment]
@freebroccolo @wilcoxjay Hmmm, this sounds interesting. We should open a ticket on RedPRL for this.
